#!/usr/bin/python3

from subprocess import os,Popen,PIPE
import sys,re

def checkUser():
    if os.geteuid() == 0:
        sys.exit('Run without sudo!!')

if __name__ == '__main__':
    checkUser()
    socks = 'torpinger -tw | tail -1'
    key = re.sub("Port: .*\/Port",'',os.popen(socks).stdout.read())

    if key == "Port":
        port = re.sub("Port: \(.*\)\/1",'',Popen(socks, stdout=subprocess.PIPE).stdout.read())
        print ("The port is {}".format(port))
        os.system("zetproxy Socks {}".format(port))
    else:
        print ('No tor, no point, exitting')
